openapi: 3.0.0
info:
  title: 'Blogging Platform API'
  version: '1.0'
paths:
  /blogging-platform-api/public/index.php/v1/posts:
    get:
      tags:
        - Get All Posts
      summary: Returns a list of Posts
      operationId: findAll
      responses:
        '200':
          description: An array of posts
          content:
            application/json:
              schema:
                type: array
                $ref: '#components/schemas/Post'
        '404':
          description: No posts have been found !
    

  /blogging-platform-api/public/index.php/v1/posts/{id}:
    get:
      tags:
      - Get A Post
      summary: Get a Post by Id
      description: Returns a single Post
      operationId: getOne
      parameters:
        - name: id
          in: path
          description: ID of Post to return
          required: true
          schema:
              type: integer
              format: int64
      responses:
          '200':
              description: A single Post
              content:
                application/json:
                  schema:
                    type: array
                    $ref: '#components/schemas/Post'
          '404':
              description: No post found !

  /blogging-platform-api/public/index.php/v1/posts?term={value}:
    get:
      tags:
      - Get Posts by term value
      summary: Get Posts by term value
      description: Returns posts that include the term value
      operationId: findByParameter
      parameters:
        - name: value
          in: path
          description: value to specify
          required: true
          schema:
              type: string
      responses:
          '200':
              description: OK
              content:
                application/json:
                  schema:
                    type: array
                    $ref: '#components/schemas/Post'
          '404':
              description: No posts found !

  /blogging-platform-api/public/index.php/v1/posts/create:
    post:
        tags:
        - Create a Post
        summary: Create a post
        description: Create a post
        operationId: create
        requestBody:
          description: Create a post
          content:
            application/json:
              schema:
                 type: object
                 properties:
                    title:
                      type: string
                      example: My Title
                    content:
                      type: string
                      example: My content
                    category:
                      type: string
                      example: Technology
                    tags:
                      type: array
                      items: string
                      example: ['PHP', 'Swagger', 'Symfony']
        required: true
        responses:
          '201':
              description: Created
          '400':
              description: 'Error : Bad Request'

  /blogging-platform-api/public/index.php/v1/posts/update/{id}:
    put:
        tags:
        - Update a Post
        summary: Update a Post
        description: Update a Post
        operationId: update
        parameters:
        - name: id
          in: path
          description: ID of Post to update
          required: true
        requestBody:
          description: Update a Post
          content:
            application/json:
              schema:
                 type: object
                 properties:
                    title:
                      type: string
                      example: My Title
                    content:
                      type: string
                      example: My content
                    category:
                      type: string
                      example: Technology
                    tags:
                      type: array
                      items: string
                      example: ['PHP', 'Swagger', 'Symfony']
        required: true
        responses:
          '200':
              description: OK

          '404':
              description: No post found !

  /blogging-platform-api/public/index.php/v1/posts/delete/{id}:
    delete:
        tags:
        - Delete a Post
        summary: Delete a Post
        description: Delete a Post
        operationId: Delete
        parameters:
        - name: id
          in: path
          description: ID of Post to delete
          required: true        
        responses:
          '204':
              description: No content

          '404':
              description: No post found !
            

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        category:
          type: string
        tags:
          type: array
          items: string
        created_at:
          type: string
        updated_at:
          type: string
      example:
              id: 1
              title: My Title
              content: My Content
              category: Technology
              tags: ['PHP', 'Swagger', 'Symfony']
              created_at: '2024-09-03T13:59:12Z'
              updated_at: '2024-09-03T13:59:12Z'
    
      